<a href="https://colab.research.google.com/github/PravalikaMuthoju/GENERATIVE-AI/blob/main/2303A52347_GEN_AI_ASS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Write Python code from scratch to find error metrics of deep learning model. Actualvalues and deep learning model predicted values are shown in Table 1.   compare the results with the outcomes of libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np


X = [[1], [2], [3], [4], [5]]
Y_actual = [20, 30, 40, 50, 60]
Y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]

# Train Linear Regression
model = LinearRegression()
model.fit(X, Y_actual)

predicted_values = model.predict(X)

mae = mean_absolute_error(Y_actual, Y_pred)
mse = mean_squared_error(Y_actual, Y_pred)
rmse = mse ** 0.5

print("Regression Metrics:")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")


Regression Metrics:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127


## 2. Write python code from scratch to find evaluation metrics of deep learning model. Actual values and deep learning model predicted values are shown in Table 2. Also compare the results with outcome of libraries

In [26]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

In [28]:

Y_actual = np.array([0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2])
Y_pred = np.array([0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2])

accuracy = accuracy_score(Y_actual, Y_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(Y_actual, Y_pred, average=None)
for i in range(len(precision)):
    print(f"Class {i} - Precision: {precision[i]:.2f}")

recall = recall_score(Y_actual, Y_pred, average=None)
for i in range(len(recall)):
    print(f"Class {i} - Recall: {recall[i]:.2f}")

f1 = f1_score(Y_actual, Y_pred, average=None)
for i in range(len(f1)):
    print(f"Class {i} - F1-Score: {f1[i]:.2f}")

conf_matrix = confusion_matrix(Y_actual, Y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

print("\nDetailed Classification Report:")
print(classification_report(Y_actual, Y_pred))


Accuracy: 0.73
Class 0 - Precision: 0.78
Class 1 - Precision: 0.71
Class 2 - Precision: 0.71
Class 0 - Recall: 0.64
Class 1 - Recall: 0.62
Class 2 - Recall: 0.91
Class 0 - F1-Score: 0.70
Class 1 - F1-Score: 0.67
Class 2 - F1-Score: 0.80

Confusion Matrix:
[[ 7  2  2]
 [ 1  5  2]
 [ 1  0 10]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        11
           1       0.71      0.62      0.67         8
           2       0.71      0.91      0.80        11

    accuracy                           0.73        30
   macro avg       0.74      0.72      0.72        30
weighted avg       0.74      0.73      0.73        30

